In [ ]:
 def Snippet_349():
   print()
   print(format('Image classification using Random Forest '))

   import warnings
   warnings.filterwarning("ignore")

In [ ]:
from keras.datasets import cifar10
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import time
start_time= time.time() 

In [ ]:
(m_train, n_train), (m_test, n_test)= cifar10.load_data()

In [ ]:
RESHAPED =3072

In [ ]:
m_train= m_train.reshape(50000, RESHAPED)
m_test= m_test.reshape(10000, RESHAPED)
m_train=m_train.astype('float32')
m_test=m_test.astype('float32')


In [ ]:
n_train=n_train.flatten()
n_test=n_test.flatten()
m_train /=25
m_test/=255

In [ ]:
print(m_train.shape[0], 'Train Sample')
print(m_test.shape[0], 'Test Sample')

50000 Train Sample
10000 Test Sample


In [ ]:
model = RandomForestClassifier(n_estimators=10)
cv_results= cross_val_score(model, m_train, n_train, cv= 2, scoring= 'accuracy', n_jobs=-1, verbose=1)

model.fit(m_train, n_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   20.5s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   20.5s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
print(); print(cv_results)
print(); print(model)


[0.34004 0.3322 ]

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [ ]:
expected_n= n_test
predicted_n=model.predict(m_test)

In [ ]:
print(); print(metrics.classification_report(expected_n, predicted_n))
print(); print(metrics.confusion_matrix(expected_n, predicted_n))

print()
print("Execution time %s seconds" % (time.time()- start_time))




              precision    recall  f1-score   support

           0       0.03      0.00      0.00      1000
           1       0.20      0.00      0.00      1000
           2       0.11      0.04      0.06      1000
           3       0.10      0.82      0.17      1000
           4       0.21      0.00      0.01      1000
           5       0.00      0.00      0.00      1000
           6       0.00      0.00      0.00      1000
           7       0.00      0.00      0.00      1000
           8       0.06      0.07      0.07      1000
           9       0.00      0.00      0.00      1000

    accuracy                           0.09     10000
   macro avg       0.07      0.09      0.03     10000
weighted avg       0.07      0.09      0.03     10000


[[  2   2  15 902   0   0   5   0  74   0]
 [ 14   1  34 851   1   0   1   0  98   0]
 [  4   0  39 843   1   0   2   0 111   0]
 [ 13   1  53 821   2   0   2   2 106   0]
 [  2   0  34 766   4   0   2   0 192   0]
 [  2   0  49 831   4   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
